//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJPlaylistsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYLIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAYLIST()
        {
            this.PLAYLIST_SONGS = new HashSet<PLAYLIST_SONG>();
            this.USER_PLAYLISTS = new HashSet<USER_PLAYLIST>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public int USER_ID { get; set; }
        public bool IS_PUBLIC { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYLIST_SONG> PLAYLIST_SONGS { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_PLAYLIST> USER_PLAYLISTS { get; set; }
    }
}
