//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJPlaylistsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SONG()
        {
            this.PLAYLIST_SONGS = new HashSet<PLAYLIST_SONG>();
            this.SONG_PLAYS = new HashSet<SONG_PLAY>();
            this.SONG_GENRES = new HashSet<SONG_GENRE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public string ARTIST_NAME { get; set; }
        public int DURATION_SECS { get; set; }
        public int YEAR { get; set; }
        public string ALBUM_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLAYLIST_SONG> PLAYLIST_SONGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONG_PLAY> SONG_PLAYS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SONG_GENRE> SONG_GENRES { get; set; }
    }
}
