//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DJPlaylistsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_PLAYLIST
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int PLAYLIST_ID { get; set; }
        public System.DateTime DATE_CREATED { get; set; }
    
        public virtual PLAYLIST PLAYLIST { get; set; }
        public virtual USER USER { get; set; }
    }
}
